### ISSUE TITLE
Traceback from KeyError

### ISSUE THREAD

**Issue by bengan** [alexst07/fbcomments#1]
Don't know much about json from facebook it looks as if "from" doesn't exist there. It crashes on every page I tried. This is the one I started with.

[A certain facebook post](https://www.facebook.com/daddario/photos/a.250339430721.302487.83728925721/10160256047215722/?type=3)

> ./fbcomments.py -a XXXXX -p https://www.facebook.com/daddario -i 10160256048450722 -f comments.txt

```
Traceback (most recent call last):
  File "./fbcomments.py", line 130, in <module>
    main()
  File "./fbcomments.py", line 124, in main
    res = list_comments(obj_id)
  File "./fbcomments.py", line 72, in list_comments
    ret_json += '"from":"' + obj["from"]["name"] + '",\n'
KeyError: 'from'
```

**Comment by tomfbush** [comment]
@bengan I think this is because FB reviewed the API and how much info you can get about users -- now the only account with which a "from" is associated is the page posting I believe.

If you change the code so that it only references `obj['created_time']`, `obj['message']` and `obj['id']` then it should work for you. I've made some very messy changes 'cos I needed this to work right now but it should only take a moment.
